# Generated by Django 5.2.1 on 2025-09-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_category_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='picture',
        ),
    ]
